### PR TITLE
feat: nuxt module

### PR DESCRIPTION
**Pull request by ineshbose**
~~https://github.com/ineshbose/nuxt-unjs-module/issues/4~~ (link may be dead)
image

(Let me know if you were thinking to convert to monorepo with `unkit/nuxt` as a separate package)

### CODE REVIEW

**Comment by ineshbose** [comment]
@pi0 - seeking advice on how to approach the build for this! (Please check my message on Discord)

**Comment by pi0** [comment]
Thanks for PR dear @ineshbose. Sorry i am busy till weekend. Will check ASAP.

**Comment by ineshbose** [comment]
Lately I've been thinking of composables like `useScule('camelCase', 'my-string')`, with the first argument as function name and second (onwards) as input. This may not be good for variable argument sizes unfortunately.

**Comment by ineshbose** [comment]
The idea I think I should sit on:

1. Use star-imports for module instead, like:
```ts
addImports({ name: '*', as: 'scule', from: 'scule' })

// then it would be used as
scule.camelCase('hello-world')
```

removing a lot of unnecessary complexities. Usage would be documented into the README.

2. Keep nuxt-module code in `nuxt/` rather than `src/nuxt/` as I'm unsure how to configure unbuild (with the usage of `nuxt-module-builder`)

I'll rework the PR at the earliest (est. ~6th May; have a lot going at the moment) 🙂

**Comment by Atinux** [comment]
I see there is a `$` prefix defined.

Could you update the readme to show the usage please?

**Comment by ineshbose** [comment]
(closing this, we can definitely discuss this at a much better/easier time)

**Pull request closed without merging**
